# Generated by Django 4.1.13 on 2024-03-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students_unit',
            field=models.ForeignKey(blank=True, help_text='только для студентов', null=True, on_delete=django.db.models.deletion.PROTECT, to='marks.studentsunit', verbose_name='группа/класс'),
        ),
    ]
