# Generated by Django 4.1.13 on 2024-03-25 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Преподаватели'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Студенты'}, on_delete=django.db.models.deletion.PROTECT, related_name='received_marks', to=settings.AUTH_USER_MODEL, verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Преподаватели'}, on_delete=django.db.models.deletion.PROTECT, related_name='set_marks', to=settings.AUTH_USER_MODEL, verbose_name='учитель'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='оценка'),
        ),
    ]
