# Generated by Django 4.1.13 on 2024-04-19 12:18

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.management import create_permissions
from django.db.models import Q

from marks.models import StudentsUnit, Subject, Appointment
from django.contrib.auth.models import Group, Permission

def seed_users(apps, scheme_editor):
    User = get_user_model()

    students = Group.objects.create(name='Студенты')
    teachers = Group.objects.create(name='Преподаватели')
    administrators = Group.objects.create(name='Администрация')

    my_group = StudentsUnit.objects.create(name='20ОА14')

    s1 = Subject.objects.create(name='Основы стандартизации')
    s2 = Subject.objects.create(name='МДК 10.01')
    s3 = Subject.objects.create(name='Алгоритмизация')
    s4 = Subject.objects.create(name='Проектирование баз данных')
    s5 = Subject.objects.create(name='МДК 11.02')

    User.objects.create_user(surname='Закревский', name='Эмир', patronymic='Александрович', phone='+79648686527', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Баринов', name='Владислав', patronymic='Дмитриевич', phone='+79648686528', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Анохина', name='Ангелина', patronymic='Алексеевна', phone='+79648686529', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Артюшин', name='Алексей', patronymic='Витальевич', phone='+79648686530', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Дудочкин', name='Алексей', patronymic='Алексеевич', phone='+79648686531', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Каспаров', name='Андрей', patronymic='Артёмович', phone='+79648686532', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Косова', name='Ангелина', patronymic='Сергеевна', phone='+79648686533', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Левина', name='Екатерина', patronymic='Витальевна', phone='+79648686534', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Лоскутова', name='Виктория', patronymic='Сергеевна', phone='+79648686535', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Макшакова', name='Милана', patronymic='Николаевна', phone='+79648686536', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Мишков', name='Александр', patronymic='Сергеевич', phone='+79648686537', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Некрасова', name='Софья', patronymic='Антоновна', phone='+79648686538', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Нефедов', name='Дмитрий', patronymic='Витальевич', phone='+79648686539', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Нуждин', name='Дмитрий', patronymic='Алексеевич', phone='+79648686540', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Петрова', name='Екатерина', patronymic='Сергеевна', phone='+79648686541', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Сигалев', name='Александр', patronymic='Алексеевич', phone='+79648686542', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Сорокина', name='Лада', patronymic='Антоновна', phone='+79648686543', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Ткаченко', name='Яна', patronymic='Витальевна', phone='+79648686544', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Трушин', name='Максим', patronymic='Владимирович', phone='+79648686545', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Чекранова', name='Анастасия', patronymic='Владимировна', phone='+79648686546', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Чупшев', name='Иван', patronymic='Алексеевич', phone='+79648686547', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Шикина', name='Ангелина', patronymic='Евгеньевна', phone='+79648686548', students_unit=my_group, password='lolita').groups.set([students])
    User.objects.create_user(surname='Шишова', name='Полина', patronymic='Петровна', phone='+79648686549', students_unit=my_group, password='lolita').groups.set([students])

    t1 = User.objects.create_user(surname='Гусарова', name='Марина', patronymic='Николаевна', phone='+79648686550', password='lolita')
    t1.groups.set([teachers])
    t2 = User.objects.create_user(surname='Матвеева', name='Лилия', patronymic='Викторовна', phone='+79648686551', password='lolita')
    t2.groups.set([teachers])
    t3 = User.objects.create_user(surname='Захарко', name='Нина', patronymic='Данииловна', phone='+79648686552', password='lolita')
    t3.groups.set([teachers])

    User.objects.create_superuser(surname='Администраторов', name='Администратор', phone='+79648686553', password='lolita').groups.set([administrators])
    User.objects.create_user(surname='Майорова', name='Ольга', patronymic='Анатольевна', phone='+79648686554', password='lolita', is_staff=True).groups.set([administrators])

    Appointment.objects.create(students_unit=my_group, subject=s4, teacher=t1, course=1, is_first_term=True)
    Appointment.objects.create(students_unit=my_group, subject=s2, teacher=t2, course=1, is_first_term=True)
    Appointment.objects.create(students_unit=my_group, subject=s1, teacher=t3, course=1, is_first_term=False)
    Appointment.objects.create(students_unit=my_group, subject=s2, teacher=t1, course=2, is_first_term=False)
    Appointment.objects.create(students_unit=my_group, subject=s3, teacher=t2, course=2, is_first_term=False)
    Appointment.objects.create(students_unit=my_group, subject=s5, teacher=t3, course=2, is_first_term=True)
    Appointment.objects.create(students_unit=my_group, subject=s1, teacher=t1, course=3, is_first_term=True)
    Appointment.objects.create(students_unit=my_group, subject=s4, teacher=t2, course=3, is_first_term=False)
    Appointment.objects.create(students_unit=my_group, subject=s2, teacher=t3, course=3, is_first_term=True)

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    teachers.permissions.add(Permission.objects.get(codename='add_mark'))
    administrators.permissions.add(*Permission.objects.filter(Q(content_type__app_label='marks') | Q(content_type__app_label='users')))

class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('users', '0002_user_students_unit'),
    ]

    operations = [
        migrations.RunPython(seed_users)
    ]
