# Generated by Django 4.1.13 on 2024-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_appointment_teacher_alter_mark_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='pub_date',
            field=models.DateField(verbose_name='дата оценивания'),
        ),
    ]
